/* Prompt Vault — 靈感庫內建模板
   此檔為主程式 prompt-vault.html 的資料模組，必須在主程式 <script> 之前載入。
   （拆分自單檔以利維護；請與 index.html / prompt-vault.html 放在同一資料夾） */
const LIB = [
  { c:"縮圖封面", ty:"image", t:"驚訝反應臉縮圖", k:"反應 臉 表情 人物",
    p:"cinematic close-up portrait of a creator with a shocked expression, bold rim lighting, high contrast, clean solid color background with large negative space on the right for title text, ultra sharp, 16:9" },
  { c:"縮圖封面", ty:"image", t:"對決比較式縮圖", k:"vs 比較 對決 分割",
    p:"split-screen thumbnail composition, left side versus right side, dramatic color contrast between warm and cool halves, bold central dividing line, clean design with space for large text, 16:9" },
  { c:"縮圖封面", ty:"image", t:"啦啦隊應援封面（母版）", k:"啦啦隊 棒球 應援 人物 中職",
    p:"請生成一張 YouTube 影片封面，以下附圖為【球團／隊名】啦啦隊【成員名】【事件描述】，不要修改人物。整體風格要有設計感、乾淨，比例16:9，標題為「【標題文字】 【日期】」" },
  { c:"縮圖封面", ty:"image", t:"極簡產品開箱封面", k:"開箱 產品 極簡",
    p:"minimalist product hero shot floating on a solid pastel background, soft studio lighting, subtle shadow, large negative space for title text, clean design, 16:9" },
  { c:"開場", ty:"video", t:"城市日出開場", k:"片頭 城市 日出 空拍",
    p:"aerial drone shot rising over a city skyline at sunrise, golden hour light, lens flare, smooth gimbal movement, cinematic color grade, 5 seconds, 24fps" },
  { c:"開場", ty:"video", t:"LOGO 粒子匯聚", k:"片頭 logo 動畫 粒子",
    p:"glowing particles converging to form a logo in a dark studio space, volumetric light, slow elegant motion, shallow depth of field, 4 seconds loop" },
  { c:"開場", ty:"video", t:"標題卡打字機", k:"片頭 標題 文字 復古",
    p:"typewriter text animation on textured paper, warm desk lamp light, vintage film grain, macro close-up of letters appearing, 3 seconds" },
  { c:"B-roll", ty:"video", t:"咖啡沖煮特寫", k:"咖啡 手沖 特寫 慢動作",
    p:"macro slow motion shot of pour-over coffee brewing, steam rising, natural window light, shallow depth of field, warm tones, 6 seconds, 60fps" },
  { c:"B-roll", ty:"video", t:"鍵盤打字特寫", k:"打字 鍵盤 工作 特寫",
    p:"close-up of hands typing on a mechanical keyboard, moody low-key lighting with subtle neon accent, shallow depth of field, tracking shot sliding sideways, 4 seconds" },
  { c:"B-roll", ty:"video", t:"街頭人流縮時", k:"城市 人群 縮時 街頭",
    p:"hyperlapse of a busy pedestrian crossing at dusk, motion-blurred crowds, city neon signs, blue hour, high vantage point, 5 seconds, 24fps" },
  { c:"B-roll", ty:"video", t:"翻書頁特寫", k:"書 閱讀 知識 特寫",
    p:"extreme close-up of book pages flipping in soft natural light, dust particles floating, shallow depth of field, slow motion, warm cozy tones, 4 seconds" },
  { c:"產品", ty:"video", t:"產品 360 旋轉展示", k:"產品 展示 旋轉 電商",
    p:"slow 360 orbit around a product on a reflective black surface, soft studio softbox lighting, subtle lens flare, macro detail, shallow depth of field, 6 seconds loop" },
  { c:"產品", ty:"image", t:"零件漂浮爆炸圖", k:"產品 拆解 科技 爆炸圖",
    p:"exploded view of a gadget with parts floating in mid-air, studio lighting on a dark background, precise technical aesthetic, subtle blue accent light, centered composition, 16:9" },
  { c:"產品", ty:"image", t:"生活情境使用照", k:"產品 情境 生活感",
    p:"lifestyle photo of a person naturally using the product in a bright modern interior, natural window light, candid feel, photorealistic, shallow depth of field, 16:9" },
  { c:"人物", ty:"image", t:"專業形象照", k:"頭像 形象照 大頭貼",
    p:"professional headshot of a creator, soft key light with gentle rim light, blurred modern office background, confident friendly expression, photorealistic, 4:5" },
  { c:"人物", ty:"image", t:"動漫風自畫像", k:"動漫 頭像 二次元",
    p:"anime style portrait of a young creator, clean cel shading, expressive eyes, soft gradient background, vibrant but harmonious colors, 1:1" },
  { c:"人物", ty:"image", t:"皮克斯風 3D 角色", k:"3d 角色 皮克斯 可愛",
    p:"Pixar style 3D character portrait, big expressive eyes, warm smile, soft studio lighting, colorful simple background, high detail render, 1:1" },
  { c:"背景", ty:"image", t:"直播虛擬背景", k:"直播 背景 房間 虛擬",
    p:"cozy streaming room interior at dusk, bookshelf with warm LED accents, soft neon glow, plants and figurines, empty desk in foreground, blue hour mood, no people, 16:9" },
  { c:"背景", ty:"image", t:"賽博龐克雨夜街景", k:"賽博 霓虹 雨 街景",
    p:"cyberpunk alley at night in the rain, neon signs reflecting on wet pavement, volumetric fog, moody teal and magenta palette, wide shot, no people, 16:9" },
  { c:"背景", ty:"image", t:"柔和漸層簡報底圖", k:"簡報 底圖 漸層 抽象",
    p:"soft abstract background with gentle flowing color transitions, muted tones, subtle grain texture, minimalist, plenty of clear space for text overlay, 16:9" },
  { c:"美食", ty:"image", t:"美食俯拍擺盤", k:"食物 俯拍 擺盤 餐廳",
    p:"top-down flat lay of a beautifully plated dish on a marble table, natural window light, fresh ingredients scattered around, shallow shadows, appetizing colors, 4:5" },
  { c:"美食", ty:"video", t:"起司拉絲慢動作", k:"起司 披薩 慢動作 誘人",
    p:"slow motion cheese pull from a hot pizza slice, steam rising, warm golden light, extreme close-up, appetizing glossy texture, 4 seconds, 60fps" },
  { c:"科技遊戲", ty:"image", t:"電競燈光房", k:"電競 rgb 房間 遊戲",
    p:"gaming setup with RGB lighting in a dark room, ultrawide monitor glow, low-key lighting, haze in the air, cinematic wide shot, no people, 16:9" },
  { c:"科技遊戲", ty:"video", t:"未來 HUD 介面動畫", k:"hud 介面 未來 科幻 疊加",
    p:"futuristic holographic HUD interface animating on a dark background, glowing cyan data panels and rotating wireframe globe, subtle glitch effects, seamless loop, 6 seconds" },
  { c:"其他", ty:"image", t:"萌寵黃金時刻特寫", k:"寵物 貓 狗 可愛",
    p:"adorable pet close-up portrait in golden hour light, backlit fur glowing, shallow depth of field, joyful expression, photorealistic, 4:5" },
  { c:"其他", ty:"video", t:"水墨暈染轉場素材", k:"轉場 水墨 素材 黑白",
    p:"black ink drop blooming in clear water, macro shot, high contrast on white background, elegant slow motion, usable as transition matte, 5 seconds, 60fps" }
];
